{% set name = "robotframework-interpreter" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/robotframework-interpreter/archive/{{ version }}.tar.gz
  sha256: a2c26c7c80db9f984124eaf6d0c7a32ee0c00c3fa072cba47bc9bd616efe19df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - robotframework >=3.2,<5
    - lunr
    - pillow
    - pygments
    - ipywidgets

test:
  imports:
    - robotframework_interpreter

about:
  home: https://github.com/jupyter-xeus/robotframework-interpreter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility functions for building a Robot Framework interpreter
  dev_url: https://github.com/jupyter-xeus/robotframework-interpreter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
