{% set name = "robotframework-interpreter" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/robotframework-interpreter/archive/{{ version }}.tar.gz
  sha256: 1a3c0baa04e7dbc8720a581adf4a05e367cc2c6a1dd36db12ed166bc43010fd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - robotframework >=3.2,<5
    - lunr
    - pillow
    - pygments
    - ipywidgets

test:
  imports:
    - robotframework_interpreter

about:
  home: https://github.com/jupyter-xeus/robotframework-interpreter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility functions for building a Robot Framework interpreter
  dev_url: https://github.com/jupyter-xeus/robotframework-interpreter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
